"""Protocol interfaces for core Arrow Lake components.

Used for type-safe component references without concrete class dependencies.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class StorageProtocol(Protocol):
    """Interface for LanceStorageManager — covers all methods called by mixin classes."""

    # --- CRUD ---
    def create_dataset(self, name: str, data: Any) -> None: ...
    def read_dataset(self, name: str, version: int | None = None, columns: list[str] | None = None) -> Any: ...
    def append_dataset(self, name: str, data: Any) -> None: ...
    def upsert_dataset(self, name: str, data: Any) -> None: ...
    def delete_rows(self, name: str, filter_expr: str) -> int: ...
    def update_rows(self, name: str, updates: dict[str, Any], filter_expr: str) -> int: ...
    def delete_dataset(self, name: str) -> None: ...
    def restore_dataset(self, name: str, data: Any) -> None: ...
    def dataset_exists(self, name: str) -> bool: ...
    def list_datasets(self) -> list[str]: ...

    # --- Open / URI ---
    def open_dataset(self, name: str, version: int | None = None) -> Any: ...
    def dataset_uri(self, name: str) -> str: ...

    # --- Versioning ---
    def get_version(self, name: str) -> int: ...
    def list_versions(self, name: str) -> list[dict[str, object]]: ...
    def create_tag(self, dataset_name: str, tag: str, version: int | None = None) -> None: ...
    def read_at_tag(self, dataset_name: str, tag: str) -> Any: ...
    def list_tags(self, dataset_name: str) -> dict[str, int]: ...
    def delete_tag(self, dataset_name: str, tag: str) -> None: ...

    # --- Schema evolution ---
    def add_column(self, name: str, column_name: str, sql_expr: str) -> None: ...
    def add_columns_table(self, name: str, columns: Any) -> None: ...
    def alter_column(self, name: str, column_name: str, new_type: Any) -> None: ...
    def drop_column(self, name: str, column_name: str) -> None: ...

    # --- Maintenance ---
    def compact(self, name: str) -> Any: ...
    def scan_dataset(self, name: str, columns: list[str] | None = None, filter_expr: str | None = None) -> Any: ...
    def cleanup_versions(self, dataset_name: str, older_than: Any, dry_run: bool = False) -> int: ...

    # --- Copy / rename / merge ---
    def copy_dataset(self, name: str, new_name: str) -> None: ...
    def rename_dataset(self, name: str, new_name: str) -> None: ...
    def merge_datasets(self, datasets: list[str], target_name: str) -> None: ...

    # --- Vector indexing ---
    def delete_vector_index(self, name: str, index_name: str) -> None: ...
    def rebuild_vector_index(self, name: str, column: str, **kwargs: Any) -> None: ...


@runtime_checkable
class EmbeddingEncoderProtocol(Protocol):
    """Minimal interface for embedding encoders."""

    def encode(self, texts: list[str]) -> Any: ...


@runtime_checkable
class KGClientProtocol(Protocol):
    """Minimal interface for knowledge graph client."""

    async def gremlin(self, query: str) -> list[dict[str, Any]]: ...
    async def get_stats(self) -> dict[str, Any]: ...
