blank_issues_enabled: false
contact_links:
  - name: Discussions / Q&A
    url: https://gitee.com/wits__sunpw/wits-infra-dintellihub/issues
    about: Ask questions and discuss usage here before opening a bug/feature.
