# Prometheus 配置
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "arrow-lake-server"
    static_configs:
      - targets: ["arrow-lake-api:8000"]
    metrics_path: "/metrics"

  - job_name: "ray-head"
    static_configs:
      - targets: ["arrow-lake-ray-head:8265"]
    metrics_path: "/metrics"

  - job_name: "minio"
    static_configs:
      - targets: ["arrow-lake-minio:9000"]
    metrics_path: "/minio/v2/metrics/cluster"
