gravitino.lance-rest.shutdown.timeout = 3000
gravitino.lance-rest.host = 0.0.0.0
gravitino.lance-rest.httpPort = 9101
gravitino.lance-rest.minThreads = 24
gravitino.lance-rest.maxThreads = 200
gravitino.lance-rest.stopTimeout = 30000
gravitino.lance-rest.idleTimeout = 30000
gravitino.lance-rest.threadPoolWorkQueueSize = 100
gravitino.lance-rest.requestHeaderSize = 131072
gravitino.lance-rest.responseHeaderSize = 131072
gravitino.lance-rest.namespace-backend = gravitino
gravitino.lance-rest.gravitino-uri = http://arrow-lake-gravitino:8090
gravitino.lance-rest.gravitino-metalake = arrow_lake
